### ISSUE TITLE
Operation name null value

### ISSUE THREAD

**Issue by kausandr** [Nastel/TNT4J#9]
java.lang.NullPointerException
 at com.nastel.jkool.tnt4j.utils.Utils.getMethodNameFromStack(Utils.java:535)
 at com.nastel.jkool.tnt4j.core.Operation.getResolvedName(Operation.java:155)
 at com.nastel.jkool.tnt4j.format.JSONFormatter.format(JSONFormatter.java:181)
 at com.nastel.jkool.tnt4j.format.JSONFormatter.format(JSONFormatter.java:107)
 at com.nastel.jkool.tnt4j.sink.FileSink.write(FileSink.java:126)
 at com.nastel.jkool.tnt4j.sink.FileEventSink._log(FileEventSink.java:97)
 at com.nastel.jkool.tnt4j.sink.AbstractEventSink.log(AbstractEventSink.java:414)
 at com.jkool.jesl.tnt4j.sink.JKCloudEventSink._log(JKCloudEventSink.java:231)
 at com.nastel.jkool.tnt4j.sink.AbstractEventSink.log(AbstractEventSink.java:414)
 at com.nastel.jkool.tnt4j.tracker.TrackerImpl.reportEvent(TrackerImpl.java:190)
 at com.nastel.jkool.tnt4j.tracker.TrackerImpl.tnt(TrackerImpl.java:443)
 at com.nastel.jkool.tnt4j.TrackingLogger.tnt(TrackingLogger.java:838)
 at com.jkool.tnt4j.streams.fields.ActivityInfo.recordActivity(ActivityInfo.java:512)
 at com.jkool.tnt4j.streams.inputs.TNTInputStream.processActivityItem(TNTInputStream.java:857)
 at com.jkool.tnt4j.streams.inputs.TNTInputStream.run(TNTInputStream.java:777)
 at java.lang.Thread.run(Thread.java:745)

**Comment by amavashev** [comment]
operation name is required, but fixed so that no NPE occurs, just returns null.
